# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [1]:
import numpy as np

a = np.full((5,5),6, dtype = int)
print("OutputOriginal array: ")
print(a)

print("6 on the border and 0 inside in the array: ")
a[1:-1,1:-1] = 0
print(a)

OutputOriginal array: 
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]
6 on the border and 0 inside in the array: 
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [2]:
import numpy as np

a = np.ones((8,8), dtype = int) * 3
print(a)

for i in range(8):
    for j in range(8):
        if (i+j) % 2 != 0:
            a[i][j] = 9

print('Checkerboard pattern-')            
print(a)

[[3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3]]
Checkerboard pattern-
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [3]:
ea = np.empty((3,4))
print(ea)

fa = np.full((3,3), 6, dtype=np.int)
print(fa)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [4]:
F = np.array([0, 12, 45.21 , 34, 99.91])
C = (F - 32.0) * (5.0/9.0)

C = np.around( C, 2)
C

array([-17.78, -11.11,   7.34,   1.11,  37.73])

In [5]:
F = (C * (9.0/5.0)) + 32

F = np.around( F, 2)
F

array([-0.  , 12.  , 45.21, 34.  , 99.91])

Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [6]:
oa = np.array([ 1.00000000 + 0.j, 0.70710678 + 0.70710678j])
oa

array([1.        +0.j        , 0.70710678+0.70710678j])

In [7]:
print("Real part of the array-")
np.real(oa)

Real part of the array-


array([1.        , 0.70710678])

In [8]:
print("Imaginary part of the array-")
np.imag(oa)

Imaginary part of the array-


array([0.        , 0.70710678])

Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [9]:
A1 = np.array([0, 10, 20, 40, 60])
A2 = np.array([0,  40])

np.searchsorted(A1,A2)

array([0, 3], dtype=int64)

In [10]:
np.isin(A1, A2)

array([ True, False, False,  True, False])

Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [11]:
A1 = np.array([0, 10, 20, 40, 60])
A2 = np.array([10, 40])
A1[np.isin(A1, A2)]

array([10, 40])

Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]


    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [12]:
oa = np.array([10, 10, 20, 20, 30, 30])
np.unique(oa)

array([10, 20, 30])

In [13]:
oa = np.array([[1, 1],
              [2, 3]])
np.unique(oa)

array([1, 2, 3])

Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [14]:
A1 = np.array([0, 10, 20, 40, 60, 80])
A2 = np.array([10, 30, 40, 50, 70])
A1[np.isin(A1, A2)] + A2[np.isin(A2, A1)]

array([20, 80])

Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [15]:
A = np.array([1,1,1,1,0])
np.all(A)

False

In [16]:
A = np.array([1,1,1,1,1])
np.all(A)

True

Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [17]:
A = np.array([[1,1,1,1,1],
              [1,0,1,1,1]]
            )

np.all(A, axis=0)

array([ True, False,  True,  True,  True])

In [18]:
np.all(A, axis=1)

array([ True, False])

Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [19]:
A = np.array([1, 2, 3, 4])

print("Original Array \n", A)
print("2 Times  Array \n", np.hstack((A,A)))
print("3 Times  Array \n", np.hstack((A,A,A)))

Original Array 
 [1 2 3 4]
2 Times  Array 
 [1 2 3 4 1 2 3 4]
3 Times  Array 
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [20]:
A = np.array([1,2,3,4,5,6])
print(" Minimum value Index: {}  Minimum Value: {}".format(np.argmin(A), np.min(A)))

 Minimum value Index: 0  Minimum Value: 1


In [21]:
print(" Maximum value Index: {}  Maximum Value: {}".format(np.argmax(A), np.max(A)))

 Maximum value Index: 5  Maximum Value: 6


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [22]:
A1 = np.array([1, 2])
A2 = np.array([4, 5])

print("A1 > A2  : ", A1 > A2)
print("A1 >= A2 : ", A1 >= A2)
print("A1 < A2  : ", A1 < A2)
print("A1 <= A2 : ", A1 <= A2)

A1 > A2  :  [False False]
A1 >= A2 :  [False False]
A1 < A2  :  [ True  True]
A1 <= A2 :  [ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [23]:
A = np.array([[4, 6],[2 ,1]])
print("Original Array \n", A1)
print('-'*60)

A1 = np.sort(A1, axis = 0)
print("First Axis Sorted Array \n", A1)
print('-'*60)

A2 = np.sort(A1, axis = -1)
print("Last Axis Sorted Array \n", A2 )
print('-'*60)

A3 = np.sort(A, axis = 1)
print("Second Axis Sorted Array \n", A3 )
print('-'*60)

Original Array 
 [1 2]
------------------------------------------------------------
First Axis Sorted Array 
 [1 2]
------------------------------------------------------------
Last Axis Sorted Array 
 [1 2]
------------------------------------------------------------
Second Axis Sorted Array 
 [[4 6]
 [1 2]]
------------------------------------------------------------


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [24]:
first_names = ['Betsey', 'Shelley', 'Lanell', 'Genesis', 'Margery']
last_names =  ['Battle', 'Plotner', 'Brien', 'Stahl', 'Woolum']

indx = np.lexsort((last_names,first_names))
indx

array([0, 3, 2, 4, 1], dtype=int64)

In [25]:
ln_array = np.array(last_names)
print("Sorted Last Names:", np.sort(ln_array))

fn_array = np.array(first_names)
print("Sorted First Names:", np.sort(fn_array) )

Sorted Last Names: ['Battle' 'Brien' 'Plotner' 'Stahl' 'Woolum']
Sorted First Names: ['Betsey' 'Genesis' 'Lanell' 'Margery' 'Shelley']


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [26]:
oa = np.array([[0, 10, 20],
               [20, 30, 40]])
print("Original array: ")
print(oa)
print('-'*60)


print(" Are Values bigger than 10? =", [oa>10] )
print('-'*60)
print(" Values bigger than 10 =", oa[oa>10])
print('-'*60)
print("Indices are ", np.nonzero(oa > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
------------------------------------------------------------
 Are Values bigger than 10? = [array([[False, False,  True],
       [ True,  True,  True]])]
------------------------------------------------------------
 Values bigger than 10 = [20 20 30 40]
------------------------------------------------------------
Indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [27]:
b = np.nonzero([[1,0,0],
               [0,1,0],
               [0,0,1]]
              )
b

(array([0, 1, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [28]:
oa > 10

array([[False, False,  True],
       [ True,  True,  True]])

Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [29]:
a = np.array( [[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6],
               [4,5,6,7] ] ,
               
               dtype=np.int)
print("Array Size = {0}      Array Item Size = {1}      Array Size in Bytes = {2}".format(a.size, a.itemsize, a.nbytes))

Array Size = 16      Array Item Size = 4      Array Size in Bytes = 64


In [30]:
a = np.array( [[1,2,3,4],
               [2,3,4,5],
               [3,4,5,6],
               [4,5,6,7] ] ,
               
               dtype=np.float)
print("Array Size = {0}      Array Item Size = {1}      Array Size in Bytes = {2}".format(a.size, a.itemsize, a.nbytes))

Array Size = 16      Array Item Size = 8      Array Size in Bytes = 128


## Great Job!