# Assignment

In [1]:
import numpy as np

Q1. Create two arrays of six elements. Write the NumPy program to
count the number of instances of a value occurring in one array on
the condition of another array.

    Sample OutputOriginal arrays-
    [ 10 -10 10 -10 -10 10]
    [0.85 0.45 0.9 0.8 0.12 0.6 ]
    Number of instances of a value occurring in one array on the condition of another
    array: 3


In [2]:
A = np.array([ 10, -10, 10, -10, -10, 10])
B = np.array([0.85, 0.45, 0.9, 0.8, 0.12, 0.6 ])


print('Number of instances A condition match: ', np.sum(A > 0))
print('Number of instances B condition match: ', np.sum(B > 0.4))

print('Number of instances of a value occurring in one array on the condition of another array: ', np.sum((A > 0) & (B > 0.4)))

Number of instances A condition match:  3
Number of instances B condition match:  5
Number of instances of a value occurring in one array on the condition of another array:  3


Q2. Write the NumPy program to convert a Python dictionary to a
Numpy ndarray ?
    
    Original dictionary-
    {'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
    'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
    'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
    'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}}
    Type: <class 'dict'>
    ndarray-
    [[ 1. 0. 0. 2.]
    [ 3. 1. 0. -1.]
    [ 4. 1. 5. -1.]
    [ 3. -1. -1. -1.]]
    Type: <class 'numpy.ndarray'>


In [20]:
OD = {
    'column0': {'a': 1, 'b': 0.0, 'c': 0.0, 'd': 2.0},
    'column1': {'a': 3.0, 'b': 1, 'c': 0.0, 'd': -1.0},
    'column2': {'a': 4, 'b': 1, 'c': 5.0, 'd': -1.0},
    'column3': {'a': 3.0, 'b': -1.0, 'c': -1.0, 'd': -1.0}
     }

In [21]:
List = []
for inner_item in OD.values():
    List.append( list(inner_item.values()) )

A = np.array(List)     
print(A)
print(type(A))

[[ 1.  0.  0.  2.]
 [ 3.  1.  0. -1.]
 [ 4.  1.  5. -1.]
 [ 3. -1. -1. -1.]]
<class 'numpy.ndarray'>


Q3. Write the Numpy program to find and store the non-zero unique
rows in an array after comparing each row with other row in the
given matrix?
 
    Original array-
    [[ 1 1 0]
    [ 0 0 0]
    [ 0 2 3]
    [ 0 0 0]
    [ 0 -1 1]
    [ 0 0 0]]
    Non-zero unique rows-
    [[ 1 1 0]
    [ 0 2 3]
    [ 0 -1 1]]

In [5]:
A = np.array([[ 1, 1, 0],[0, 0, 0],[0, 2, 3],[0, 0, 0],[0, -1, 1],[0, 0, 0]])
print('Original Array: \n', A)

print('Non-zero elements of the array: \n', A[np.nonzero(A)])

NonZeroList = []
for i in range(0,len(A)):
    if np.array_equal(A[i],np.array([0,0,0])) == False:
        NonZeroList.append(A[i])

NonZeroArray = np.array(NonZeroList)
print('Non-zero rows: \n', NonZeroArray)

Original Array: 
 [[ 1  1  0]
 [ 0  0  0]
 [ 0  2  3]
 [ 0  0  0]
 [ 0 -1  1]
 [ 0  0  0]]
Non-zero elements of the array: 
 [ 1  1  2  3 -1  1]
Non-zero rows: 
 [[ 1  1  0]
 [ 0  2  3]
 [ 0 -1  1]]


Q4. Write the NumPy program to multiply the matrix by another matrix
of complex numbers and create a new matrix of complex
numbers?

    Sample outputFirst array-
    [ 1.+2.j 3.+4.j]
    Second array-
    [ 5.+6.j 7.+8.j]
    Product of above two arrays-
    (70-8j)

In [6]:
A = np.array([ 1.+2.j , 3.+4.j])
B = np.array([ 5.+6.j , 7.+8.j])

print('Dot Product Arrays: \n',np.dot(A,B))

print('Dot Product Arrays: \n',A@B)

print('Element Product: \n', np.multiply(A,B))

print('Dot Product of Vectors: \n', np.vdot(A,B))

Dot Product Arrays: 
 (-18+68j)
Dot Product Arrays: 
 (-18+68j)
Element Product: 
 [ -7.+16.j -11.+52.j]
Dot Product of Vectors: 
 (70-8j)


Q5. Write a NumPy program to generate the matrix product of two
Arrays?

    Sample OutputMatrices and vectors.
    x-
    [[1, 0], [1, 1]]
    y-
    [[3, 1], [2, 2]]
    Matrix product of above two arrays-
    [[3 1]
    [5 3]]


In [7]:
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])

print('Dot Product Arrays: \n',np.dot(x,y))

print('Dot Product Arrays: \n',x@y)

Dot Product Arrays: 
 [[3 1]
 [5 3]]
Dot Product Arrays: 
 [[3 1]
 [5 3]]


Q6. Write the NumPy program to find roots of the following Polynomials?

    a) (x2 - 4x + 7)
    b) x4 - 11x3 + 9x2 + 11x - 10
    Sample outputRoots of the first polynomial-
    [ 1. 1.]
    Roots of the second polynomial-
    [ 11.04461946+0.j -0.87114210+0.j 0.91326132+0.4531004j  0.91326132-0.4531004j ]

In [8]:
print("Roots of the first polynomial -> x2 - 4x + 7: \n", np.roots([1, -4, 7]))

print("Roots of the second polynomial -> x4 - 11x3 + 9x2 + 11x - 10: \n",np.roots([1, -11, 9, 11, -10]))


Roots of the first polynomial -> x2 - 4x + 7: 
 [2.+1.73205081j 2.-1.73205081j]
Roots of the second polynomial -> x4 - 11x3 + 9x2 + 11x - 10: 
 [10.+0.0000000e+00j -1.+0.0000000e+00j  1.+9.6357437e-09j
  1.-9.6357437e-09j]


Q7. Write the NumPy program to calculate inverse of sine, cosine,
and inverse tangent for all elements in a given array?

    Sample output
    Inverse sine- [-1.57079633 0. 1.57079633]
    Inverse cosine- [3.14159265 1.57079633 0. ]
    Inverse tangent- [-0.78539816 0. 0.78539816]

In [9]:
A = np.array([-1., 0, 1.])
print('Sine Inverse: \n', np.arcsin(A))
print('Cosine Inverse: \n', np.arccos(A))
print('Tangent Inverse: \n', np.arctan(A))

print('Sine Hyperbolic: \n', np.sinh(A))
print('Cosine Hyperbolic: \n', np.cosh(A))
print('Tangent Hyperbolic: \n', np.tanh(A))

Sine Inverse: 
 [-1.57079633  0.          1.57079633]
Cosine Inverse: 
 [3.14159265 1.57079633 0.        ]
Tangent Inverse: 
 [-0.78539816  0.          0.78539816]
Sine Hyperbolic: 
 [-1.17520119  0.          1.17520119]
Cosine Hyperbolic: 
 [1.54308063 1.         1.54308063]
Tangent Hyperbolic: 
 [-0.76159416  0.          0.76159416]


Q8. Write the NumPy program to calculate the difference between in
neighbouring elements, element-wise of a given array?

    Sample outputOriginal array-
    [1 3 5 7 0]
    Difference between neighbouring elements, element-wise of the said array-
    [ 2 2 2 -7]

In [10]:
A = np.array([1, 3, 5, 7, 0])

np.diff(A, n=1)

array([ 2,  2,  2, -7])

Q9. Write the Python program to find the maximum and the minimum
value of a given flattened array?

    Expected OutputOriginal flattened array-
    [[0 1]
    [2 3]]
    Maximum value of the above flattened array3
    Minimum value of the above flattened array0

In [11]:
A = np.array([[0, 1],[2, 3]])
print('Max Value:',np.max(A))
print('Min Value:',np.min(A))

Max Value: 3
Min Value: 0


Q10. Write the NumPy program to calculate the difference between in
the maximum and the minimum values of a given array along the
second axis ?

    Expected OutputOriginal array-
    [[ 0 1 2 3 4 5]
    [ 6 7 8 9 10 11]]
    Difference between the maximum and the minimum values of the said array-
    [5 5]


In [12]:
A = np.arange(0,12)
A = np.array(np.split(A, [6], axis = 0))

print('Original Array: \n', A)

Original Array: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


Q11. Write the NumPy program to compute the weighted of the given
array ?

    Sample OutputOriginal array-
    [0 1 2 3 4]
    Weighted average of the said array 2.6666666666666665

In [13]:
A = np.arange(0,5)
print('Original Array: \n', A)

print('Weighted Average: \n', np.average(A, weights = np.arange(0, 5)))

print('Weighted Average: \n', np.average(A, weights = np.arange(0, 50, 10)))

print('Weighted Average: \n', np.average(A, weights = np.arange(0, 2.5, 0.5)))

print('Weighted Average: \n', np.average(A, weights = np.arange(1, 6)))

Original Array: 
 [0 1 2 3 4]
Weighted Average: 
 3.0
Weighted Average: 
 3.0
Weighted Average: 
 3.0
Weighted Average: 
 2.6666666666666665


Q12. Write the NumPy program to compute the mean, standard
deviation, and the variance of a given array along the second
axis?

    Sample outputOriginal array-
    [0 1 2 3 4 5]
    Mean- 2.5
    std- 1
    variance- 2.9166666666666665

In [14]:
A = np.arange(0,6)
print('Original Array: \n', A)

print('Mean: \n', np.mean(A))

print('Standard Deviation: \n', np.std(A, axis=0))

print('Variance: \n', np.var(A, axis=0))

Original Array: 
 [0 1 2 3 4 5]
Mean: 
 2.5
Standard Deviation: 
 1.707825127659933
Variance: 
 2.9166666666666665


Q13. Write the Numpy program to compute the covariance matrix of the
two given arrays?
    
    Sample OutputOriginal array1-
    [0 1 2]
    Original array1-
    [2 1 0]
    Covariance matrix of the said arrays-
    [[ 1. -1.]
    [-1. 1.]]

In [15]:
A = np.array([0, 1, 2])
B = np.array([2, 1, 0])

print('Covariance matrix of A wrt B:\n', np.cov(A, B))

Covariance matrix of A wrt B:
 [[ 1. -1.]
 [-1.  1.]]


Q14. Write a NumPy program to compute the cross-correlation of two
given arrays ?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Cross-correlation of the said arrays-
    [ [ 2.33333333 2.16666667 ]
     [ 2.16666667 2.33333333 ] ]

In [16]:
A = np.array([0, 1, 3])
B = np.array([2, 4, 5])

print('Cross-correlation matrix of A wrt B:\n', np.cov(A, B))

Cross-correlation matrix of A wrt B:
 [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


Q15. Write the NumPy program to compute Pearson product-moment
correlation coefficients of two given arrays?

    Sample OutputOriginal array1-
    [0 1 3]
    Original array1-
    [2 4 5]
    Pearson product-moment correlation coefficients of the said arrays-
    [[1. 0.92857143]
    [0.92857143 1. ]]

In [17]:
A = np.array([0, 1, 3])
B = np.array([2, 4, 5])

print('Pearson product-moment correlation coefficients matrix of A wrt B:\n', np.corrcoef(A, B))

Pearson product-moment correlation coefficients matrix of A wrt B:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


Q16. Write the python program to count the number of occurrences of
each value in a given array of non-negative integers?
 
Note: bincount() Function- It count the occurrence of each value in an array of the
non- negative integers in the range of the array between the minimum and maximum values
including the values that did not occur.

    Sample OutputOriginal array-
    [0, 1, 6, 1, 4, 1, 2, 2, 7]
    Number of occurrences of each value in array-
    [1 3 2 0 1 0 1 1]

In [18]:
A = np.array([0, 1, 6, 1, 4, 1, 2, 2, 7])
print('Original array: \n', A)

print('Number of occurrences of each value in array: \n', np.bincount(A))

Original array: 
 [0 1 6 1 4 1 2 2 7]
Number of occurrences of each value in array: 
 [1 3 2 0 1 0 1 1]


Q17. Write a Numpy program to compute the histogram of nums
against the bins?

    Sample Outputnums- [0.5 0.7 1. 1.2 1.3 2.1]
    bins- [0 1 2 3]
    Result- (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))

In [19]:
A = np.array([0.5, 0.7, 1., 1.2, 1.3, 2.1])
print('Original array - A: \n', A)

bins = np.arange(4)


print('Histogram of Numbers in A against bins: \n', np.histogram(A,bins))



Original array - A: 
 [0.5 0.7 1.  1.2 1.3 2.1]
Histogram of Numbers in A against bins: 
 (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))


## Great Job!